In [3]:
import numpy as np
import pandas as pd

In [5]:
print(np)

<module 'numpy' from '/Users/saykarim/Desktop/ai-ml/u-tube/movie-recommender/myenv/lib/python3.13/site-packages/numpy/__init__.py'>

In [6]:
data = pd.read_csv('Bengaluru_House_Data.csv')

In [7]:
data.head(2)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00

In [8]:
data.shape

(13320, 9)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [11]:
for column in data.columns:
    print(data[column].value_counts())
    print("*" * 20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Prarkll     1
G harth     1
Anair A     1
MasicCl     1
KPhtsei     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [12]:
print(data.columns)

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [14]:
## to check null values for all columns

data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [15]:
data.drop(columns=['area_type', 'availability', 'society', 'balcony'], inplace=True)

In [16]:
data.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [17]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [21]:
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [22]:
data['location'] = data['location'].fillna('Sarjapur Road')

In [23]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [24]:
data['size'] = data['size'].fillna('2 BHK')

In [25]:
data['bath'] = data['bath'].fillna(data['bath'].median())

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [27]:
data['bhk'] = data['size'].str.split().str.get(0).astype(int)

In [28]:
data[data.bhk > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [30]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [32]:
def convertRange(x):
    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1])) / 2
    try:
        return float(x)
    except:
        return None

In [33]:
data['total_sqft'] = data['total_sqft'].apply(convertRange)

In [34]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

## price per square feet

In [36]:
data['price_per_sqft'] = data['price'] * 100000 / data['total_sqft']

In [37]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [38]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [39]:
data['location'].value_counts()

location
Whitefield             540
Sarjapur  Road         399
Electronic City        302
Kanakpura Road         273
Thanisandra            234
                      ...
Chuchangatta Colony      1
Chikkajala               1
Udayagiri                1
pavitra paradise         1
Chikbasavanapura         1
Name: count, Length: 1306, dtype: int64

In [40]:
data['location'] = data['location'].apply(lambda x: x.strip())

In [44]:
location_count = data['location'].value_counts()

In [45]:
location_count

location
Whitefield                541
Sarjapur  Road            399
Electronic City           304
Kanakpura Road            273
Thanisandra               237
                         ...
Xavier Layout               1
Ramanagara Channapatna      1
Maheswari Nagar             1
Hsr layout sector3          1
Thyagraj Nagar              1
Name: count, Length: 1295, dtype: int64

In [42]:
location_count_less_10 = location_count[location_count <= 10]

In [48]:
location_count_less_10

location
1st Block Koramangala     10
Dairy Circle              10
Nagadevanahalli           10
Sadashiva Nagar           10
Naganathapura             10
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1054, dtype: int64

In [49]:
data['location'] = data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [50]:
data['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

## Outlier detection and removal

In [51]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [52]:
(data['total_sqft'] / data['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [53]:
data = data[(data['total_sqft'] / data['bhk']) >= 300]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [54]:

data.shape

(12530, 7)

In [56]:
data.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [57]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        gen_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]
        df_output = pd.concat([df_output, gen_df], ignore_index=True)
    return df_output

data = remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [63]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
            print(location, bhk_stats)
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values
                )
    return df.drop(exclude_indices, axis='index')

In [64]:
data = bhk_outlier_remover(data)

1st Block Jayanagar {2: {'mean': np.float64(11983.805668016194), 'std': np.float64(0.0), 'count': 1}}
1st Block Jayanagar {2: {'mean': np.float64(11983.805668016194), 'std': np.float64(0.0), 'count': 1}, 3: {'mean': np.float64(11756.16905248807), 'std': np.float64(701.6243657657865), 'count': 3}}
1st Block Jayanagar {2: {'mean': np.float64(11983.805668016194), 'std': np.float64(0.0), 'count': 1}, 3: {'mean': np.float64(11756.16905248807), 'std': np.float64(701.6243657657865), 'count': 3}, 4: {'mean': np.float64(15018.711280365416), 'std': np.float64(1.2278182423353805), 'count': 3}}
1st Phase JP Nagar {1: {'mean': np.float64(5952.380952380952), 'std': np.float64(0.0), 'count': 1}}
1st Phase JP Nagar {1: {'mean': np.float64(5952.380952380952), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(7931.806799837383), 'std': np.float64(1534.1422783514056), 'count': 8}}
1st Phase JP Nagar {1: {'mean': np.float64(5952.380952380952), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(7931.806799837383), 'std': np.float64(1534.1422783514056), 'count': 8}, 3: {'mean': np.float64(9383.571344338887), 'std': np.float64(959.0976099470785), 'count': 6}}
1st Phase JP Nagar {1: {'mean': np.float64(5952.380952380952), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(7931.806799837383), 'std': np.float64(1534.1422783514056), 'count': 8}, 3: {'mean': np.float64(9383.571344338887), 'std': np.float64(959.0976099470785), 'count': 6}, 5: {'mean': np.float64(5666.666666666667), 'std': np.float64(0.0), 'count': 1}}
2nd Phase Judicial Layout {2: {'mean': np.float64(3851.8518518518517), 'std': np.float64(497.593660834978), 'count': 3}}
2nd Phase Judicial Layout {2: {'mean': np.float64(3851.8518518518517), 'std': np.float64(497.593660834978), 'count': 3}, 3: {'mean': np.float64(3620.93991671624), 'std': np.float64(241.87983343248052), 'count': 5}}
2nd Stage Nagarbhavi {4: {'mean': np.float64(15891.203703703704), 'std': np.float64(1668.9846920398563), 'count': 4}}
2nd Stage Nagarbhavi {4: {'mean': np.float64(15891.203703703704), 'std': np.float64(1668.9846920398563), 'count': 4}, 6: {'mean': np.float64(16891.666666666668), 'std': np.float64(1858.333333333333), 'count': 2}}
5th Block Hbr Layout {2: {'mean': np.float64(4755.410708222867), 'std': np.float64(374.06419031565235), 'count': 3}}
5th Block Hbr Layout {2: {'mean': np.float64(4755.410708222867), 'std': np.float64(374.06419031565235), 'count': 3}, 3: {'mean': np.float64(5511.811023622047), 'std': np.float64(0.0), 'count': 1}}
5th Block Hbr Layout {2: {'mean': np.float64(4755.410708222867), 'std': np.float64(374.06419031565235), 'count': 3}, 3: {'mean': np.float64(5511.811023622047), 'std': np.float64(0.0), 'count': 1}, 5: {'mean': np.float64(3611.1111111111113), 'std': np.float64(0.0), 'count': 1}}
5th Block Hbr Layout {2: {'mean': np.float64(4755.410708222867), 'std': np.float64(374.06419031565235), 'count': 3}, 3: {'mean': np.float64(5511.811023622047), 'std': np.float64(0.0), 'count': 1}, 5: {'mean': np.float64(3611.1111111111113), 'std': np.float64(0.0), 'count': 1}, 6: {'mean': np.float64(5882.35294117647), 'std': np.float64(0.0), 'count': 1}}
5th Phase JP Nagar {1: {'mean': np.float64(4628.623188405797), 'std': np.float64(371.376811594203), 'count': 2}}
5th Phase JP Nagar {1: {'mean': np.float64(4628.623188405797), 'std': np.float64(371.376811594203), 'count': 2}, 2: {'mean': np.float64(5067.359785883266), 'std': np.float64(453.24956183513086), 'count': 17}}
5th Phase JP Nagar {1: {'mean': np.float64(4628.623188405797), 'std': np.float64(371.376811594203), 'count': 2}, 2: {'mean': np.float64(5067.359785883266), 'std': np.float64(453.24956183513086), 'count': 17}, 3: {'mean': np.float64(5745.003315335795), 'std': np.float64(138.40711562188537), 'count': 3}}
5th Phase JP Nagar {1: {'mean': np.float64(4628.623188405797), 'std': np.float64(371.376811594203), 'count': 2}, 2: {'mean': np.float64(5067.359785883266), 'std': np.float64(453.24956183513086), 'count': 17}, 3: {'mean': np.float64(5745.003315335795), 'std': np.float64(138.40711562188537), 'count': 3}, 5: {'mean': np.float64(4325.0), 'std': np.float64(75.0), 'count': 2}}
6th Phase JP Nagar {2: {'mean': np.float64(5932.976565810137), 'std': np.float64(671.9347030151997), 'count': 8}}
6th Phase JP Nagar {2: {'mean': np.float64(5932.976565810137), 'std': np.float64(671.9347030151997), 'count': 8}, 3: {'mean': np.float64(8403.2863080867), 'std': np.float64(1515.4146231166221), 'count': 5}}
6th Phase JP Nagar {2: {'mean': np.float64(5932.976565810137), 'std': np.float64(671.9347030151997), 'count': 8}, 3: {'mean': np.float64(8403.2863080867), 'std': np.float64(1515.4146231166221), 'count': 5}, 4: {'mean': np.float64(7704.160246533128), 'std': np.float64(0.0), 'count': 1}}
7th Phase JP Nagar {1: {'mean': np.float64(6133.333333333334), 'std': np.float64(133.33333333333348), 'count': 2}}
7th Phase JP Nagar {1: {'mean': np.float64(6133.333333333334), 'std': np.float64(133.33333333333348), 'count': 2}, 2: {'mean': np.float64(6272.516842644273), 'std': np.float64(1012.7881476778178), 'count': 40}}
7th Phase JP Nagar {1: {'mean': np.float64(6133.333333333334), 'std': np.float64(133.33333333333348), 'count': 2}, 2: {'mean': np.float64(6272.516842644273), 'std': np.float64(1012.7881476778178), 'count': 40}, 3: {'mean': np.float64(7218.681092532308), 'std': np.float64(535.2159215541863), 'count': 43}}
7th Phase JP Nagar {1: {'mean': np.float64(6133.333333333334), 'std': np.float64(133.33333333333348), 'count': 2}, 2: {'mean': np.float64(6272.516842644273), 'std': np.float64(1012.7881476778178), 'count': 40}, 3: {'mean': np.float64(7218.681092532308), 'std': np.float64(535.2159215541863), 'count': 43}, 4: {'mean': np.float64(7510.986815821015), 'std': np.float64(0.0), 'count': 1}}
8th Phase JP Nagar {1: {'mean': np.float64(6357.427937915743), 'std': np.float64(267.1694064501245), 'count': 4}}
8th Phase JP Nagar {1: {'mean': np.float64(6357.427937915743), 'std': np.float64(267.1694064501245), 'count': 4}, 2: {'mean': np.float64(4324.406715739656), 'std': np.float64(1131.8308808521078), 'count': 22}}
8th Phase JP Nagar {1: {'mean': np.float64(6357.427937915743), 'std': np.float64(267.1694064501245), 'count': 4}, 2: {'mean': np.float64(4324.406715739656), 'std': np.float64(1131.8308808521078), 'count': 22}, 3: {'mean': np.float64(5064.470856921577), 'std': np.float64(393.715985623207), 'count': 7}}
8th Phase JP Nagar {1: {'mean': np.float64(6357.427937915743), 'std': np.float64(267.1694064501245), 'count': 4}, 2: {'mean': np.float64(4324.406715739656), 'std': np.float64(1131.8308808521078), 'count': 22}, 3: {'mean': np.float64(5064.470856921577), 'std': np.float64(393.715985623207), 'count': 7}, 5: {'mean': np.float64(4335.260115606937), 'std': np.float64(0.0), 'count': 1}}
9th Phase JP Nagar {1: {'mean': np.float64(3333.3333333333335), 'std': np.float64(0.0), 'count': 1}}
9th Phase JP Nagar {1: {'mean': np.float64(3333.3333333333335), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4653.05138390364), 'std': np.float64(834.4408302683471), 'count': 20}}
9th Phase JP Nagar {1: {'mean': np.float64(3333.3333333333335), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4653.05138390364), 'std': np.float64(834.4408302683471), 'count': 20}, 3: {'mean': np.float64(5224.022319996697), 'std': np.float64(405.2117783203639), 'count': 4}}
9th Phase JP Nagar {1: {'mean': np.float64(3333.3333333333335), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4653.05138390364), 'std': np.float64(834.4408302683471), 'count': 20}, 3: {'mean': np.float64(5224.022319996697), 'std': np.float64(405.2117783203639), 'count': 4}, 4: {'mean': np.float64(5900.0), 'std': np.float64(100.0), 'count': 2}}
AECS Layout {2: {'mean': np.float64(4921.300339526721), 'std': np.float64(619.6355499375203), 'count': 7}}
Abbigere {1: {'mean': np.float64(3310.9205535075066), 'std': np.float64(610.6480739434737), 'count': 2}}
Abbigere {1: {'mean': np.float64(3310.9205535075066), 'std': np.float64(610.6480739434737), 'count': 2}, 2: {'mean': np.float64(4058.165803016323), 'std': np.float64(62.235187280114864), 'count': 13}}
Abbigere {1: {'mean': np.float64(3310.9205535075066), 'std': np.float64(610.6480739434737), 'count': 2}, 2: {'mean': np.float64(4058.165803016323), 'std': np.float64(62.235187280114864), 'count': 13}, 6: {'mean': np.float64(3165.4545454545455), 'std': np.float64(74.5454545454545), 'count': 2}}
Abbigere {1: {'mean': np.float64(3310.9205535075066), 'std': np.float64(610.6480739434737), 'count': 2}, 2: {'mean': np.float64(4058.165803016323), 'std': np.float64(62.235187280114864), 'count': 13}, 6: {'mean': np.float64(3165.4545454545455), 'std': np.float64(74.5454545454545), 'count': 2}, 8: {'mean': np.float64(5000.0), 'std': np.float64(0.0), 'count': 1}}
Akshaya Nagar {2: {'mean': np.float64(4781.22783734999), 'std': np.float64(453.10974836521865), 'count': 17}}
Akshaya Nagar {2: {'mean': np.float64(4781.22783734999), 'std': np.float64(453.10974836521865), 'count': 17}, 3: {'mean': np.float64(5419.641725942525), 'std': np.float64(418.9960108839415), 'count': 26}}
Ambalipura {1: {'mean': np.float64(5690.909090909091), 'std': np.float64(0.0), 'count': 1}}
Ambalipura {1: {'mean': np.float64(5690.909090909091), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(5886.737386783397), 'std': np.float64(736.0640513407117), 'count': 10}}
Ambalipura {1: {'mean': np.float64(5690.909090909091), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(5886.737386783397), 'std': np.float64(736.0640513407117), 'count': 10}, 3: {'mean': np.float64(6609.430031636347), 'std': np.float64(427.96315402285194), 'count': 5}}
Ambedkar Nagar {2: {'mean': np.float64(6454.091928430547), 'std': np.float64(182.0843219299883), 'count': 5}}
Ambedkar Nagar {2: {'mean': np.float64(6454.091928430547), 'std': np.float64(182.0843219299883), 'count': 5}, 3: {'mean': np.float64(6572.746532916982), 'std': np.float64(422.13464472691317), 'count': 19}}
Ambedkar Nagar {2: {'mean': np.float64(6454.091928430547), 'std': np.float64(182.0843219299883), 'count': 5}, 3: {'mean': np.float64(6572.746532916982), 'std': np.float64(422.13464472691317), 'count': 19}, 4: {'mean': np.float64(7684.086312870249), 'std': np.float64(531.2111375546801), 'count': 2}}
Amruthahalli {1: {'mean': np.float64(4020.618556701031), 'std': np.float64(0.0), 'count': 1}}
Amruthahalli {1: {'mean': np.float64(4020.618556701031), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4953.838379629301), 'std': np.float64(823.6966143070669), 'count': 12}}
Amruthahalli {1: {'mean': np.float64(4020.618556701031), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4953.838379629301), 'std': np.float64(823.6966143070669), 'count': 12}, 3: {'mean': np.float64(6444.500565010444), 'std': np.float64(463.0489537402297), 'count': 4}}
Anandapura {2: {'mean': np.float64(4335.741837049203), 'std': np.float64(710.6695705040866), 'count': 14}}
Anandapura {2: {'mean': np.float64(4335.741837049203), 'std': np.float64(710.6695705040866), 'count': 14}, 3: {'mean': np.float64(5364.840989399294), 'std': np.float64(135.15901060070655), 'count': 2}}
Anandapura {2: {'mean': np.float64(4335.741837049203), 'std': np.float64(710.6695705040866), 'count': 14}, 3: {'mean': np.float64(5364.840989399294), 'std': np.float64(135.15901060070655), 'count': 2}, 4: {'mean': np.float64(5145.797598627787), 'std': np.float64(0.0), 'count': 1}}
Ananth Nagar {1: {'mean': np.float64(2800.0), 'std': np.float64(0.0), 'count': 4}}
Ananth Nagar {1: {'mean': np.float64(2800.0), 'std': np.float64(0.0), 'count': 4}, 2: {'mean': np.float64(3015.4242497371583), 'std': np.float64(491.5389870277812), 'count': 19}}
Ananth Nagar {1: {'mean': np.float64(2800.0), 'std': np.float64(0.0), 'count': 4}, 2: {'mean': np.float64(3015.4242497371583), 'std': np.float64(491.5389870277812), 'count': 19}, 3: {'mean': np.float64(3428.8499326948368), 'std': np.float64(244.61945506026518), 'count': 2}}
Anekal {1: {'mean': np.float64(3307.549188983317), 'std': np.float64(602.8526665064047), 'count': 6}}
Anekal {1: {'mean': np.float64(3307.549188983317), 'std': np.float64(602.8526665064047), 'count': 6}, 2: {'mean': np.float64(3932.3021034454214), 'std': np.float64(398.98496492841775), 'count': 10}}
Anekal {1: {'mean': np.float64(3307.549188983317), 'std': np.float64(602.8526665064047), 'count': 6}, 2: {'mean': np.float64(3932.3021034454214), 'std': np.float64(398.98496492841775), 'count': 10}, 3: {'mean': np.float64(4305.950534298518), 'std': np.float64(347.61720096518434), 'count': 2}}
Anekal {1: {'mean': np.float64(3307.549188983317), 'std': np.float64(602.8526665064047), 'count': 6}, 2: {'mean': np.float64(3932.3021034454214), 'std': np.float64(398.98496492841775), 'count': 10}, 3: {'mean': np.float64(4305.950534298518), 'std': np.float64(347.61720096518434), 'count': 2}, 4: {'mean': np.float64(3000.0), 'std': np.float64(0.0), 'count': 1}}
Anjanapura {2: {'mean': np.float64(3451.5654968214635), 'std': np.float64(402.7964034804156), 'count': 7}}
Anjanapura {2: {'mean': np.float64(3451.5654968214635), 'std': np.float64(402.7964034804156), 'count': 7}, 3: {'mean': np.float64(5444.052006089107), 'std': np.float64(1921.703660413014), 'count': 3}}
Anjanapura {2: {'mean': np.float64(3451.5654968214635), 'std': np.float64(402.7964034804156), 'count': 7}, 3: {'mean': np.float64(5444.052006089107), 'std': np.float64(1921.703660413014), 'count': 3}, 4: {'mean': np.float64(3852.102102102102), 'std': np.float64(796.5465465465463), 'count': 2}}
Ardendale {2: {'mean': np.float64(5596.405228758171), 'std': np.float64(122.54901960784309), 'count': 2}}
Ardendale {2: {'mean': np.float64(5596.405228758171), 'std': np.float64(122.54901960784309), 'count': 2}, 3: {'mean': np.float64(5378.1844320453965), 'std': np.float64(324.88136834734956), 'count': 10}}
Ardendale {2: {'mean': np.float64(5596.405228758171), 'std': np.float64(122.54901960784309), 'count': 2}, 3: {'mean': np.float64(5378.1844320453965), 'std': np.float64(324.88136834734956), 'count': 10}, 4: {'mean': np.float64(6686.6349329114755), 'std': np.float64(326.3686552446361), 'count': 6}}
Arekere {1: {'mean': np.float64(4666.666666666667), 'std': np.float64(0.0), 'count': 1}}
Arekere {1: {'mean': np.float64(4666.666666666667), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4884.730750645279), 'std': np.float64(371.1132245946985), 'count': 6}}
Arekere {1: {'mean': np.float64(4666.666666666667), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4884.730750645279), 'std': np.float64(371.1132245946985), 'count': 6}, 3: {'mean': np.float64(5822.747277384037), 'std': np.float64(695.6480303741811), 'count': 3}}
Arekere {1: {'mean': np.float64(4666.666666666667), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(4884.730750645279), 'std': np.float64(371.1132245946985), 'count': 6}, 3: {'mean': np.float64(5822.747277384037), 'std': np.float64(695.6480303741811), 'count': 3}, 4: {'mean': np.float64(5239.852398523985), 'std': np.float64(0.0), 'count': 1}}
Attibele {1: {'mean': np.float64(2823.0512983538965), 'std': np.float64(440.8851261837879), 'count': 18}}
Attibele {1: {'mean': np.float64(2823.0512983538965), 'std': np.float64(440.8851261837879), 'count': 18}, 2: {'mean': np.float64(3667.317943144971), 'std': np.float64(359.7354006771459), 'count': 7}}
Attibele {1: {'mean': np.float64(2823.0512983538965), 'std': np.float64(440.8851261837879), 'count': 18}, 2: {'mean': np.float64(3667.317943144971), 'std': np.float64(359.7354006771459), 'count': 7}, 3: {'mean': np.float64(4941.176470588235), 'std': np.float64(889.5134291932357), 'count': 3}}
Attibele {1: {'mean': np.float64(2823.0512983538965), 'std': np.float64(440.8851261837879), 'count': 18}, 2: {'mean': np.float64(3667.317943144971), 'std': np.float64(359.7354006771459), 'count': 7}, 3: {'mean': np.float64(4941.176470588235), 'std': np.float64(889.5134291932357), 'count': 3}, 4: {'mean': np.float64(3840.959409594096), 'std': np.float64(540.9594095940961), 'count': 2}}
BEML Layout {2: {'mean': np.float64(5944.048212904286), 'std': np.float64(1628.8084083258766), 'count': 6}}
BEML Layout {2: {'mean': np.float64(5944.048212904286), 'std': np.float64(1628.8084083258766), 'count': 6}, 5: {'mean': np.float64(9375.0), 'std': np.float64(0.0), 'count': 1}}
BTM 2nd Stage {2: {'mean': np.float64(5621.791028153005), 'std': np.float64(795.7682556051348), 'count': 14}}
BTM 2nd Stage {2: {'mean': np.float64(5621.791028153005), 'std': np.float64(795.7682556051348), 'count': 14}, 3: {'mean': np.float64(12027.278254616385), 'std': np.float64(2272.2634675440436), 'count': 7}}
BTM 2nd Stage {2: {'mean': np.float64(5621.791028153005), 'std': np.float64(795.7682556051348), 'count': 14}, 3: {'mean': np.float64(12027.278254616385), 'std': np.float64(2272.2634675440436), 'count': 7}, 5: {'mean': np.float64(13913.04347826087), 'std': np.float64(0.0), 'count': 1}}
BTM Layout {1: {'mean': np.float64(4444.444444444444), 'std': np.float64(0.0), 'count': 1}}
BTM Layout {1: {'mean': np.float64(4444.444444444444), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(5073.776447337828), 'std': np.float64(424.90705275056126), 'count': 4}}
BTM Layout {1: {'mean': np.float64(4444.444444444444), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(5073.776447337828), 'std': np.float64(424.90705275056126), 'count': 4}, 3: {'mean': np.float64(5685.2029893641175), 'std': np.float64(881.6401846985812), 'count': 7}}
BTM Layout {1: {'mean': np.float64(4444.444444444444), 'std': np.float64(0.0), 'count': 1}, 2: {'mean': np.float64(5073.776447337828), 'std': np.float64(424.90705275056126), 'count': 4}, 3: {'mean': np.float64(5685.2029893641175), 'std': np.float64(881.6401846985812), 'count': 7}, 6: {'mean': np.float64(5000.0), 'std': np.float64(0.0), 'count': 1}}
Babusapalaya {2: {'mean': np.float64(3799.9594889549185), 'std': np.float64(423.8304869618116), 'count': 11}}
Babusapalaya {2: {'mean': np.float64(3799.9594889549185), 'std': np.float64(423.8304869618116), 'count': 11}, 3: {'mean': np.float64(4373.329593043904), 'std': np.float64(191.99571142920618), 'count': 4}}
Badavala Nagar {2: {'mean': np.float64(6357.9277864992155), 'std': np.float64(0.0), 'count': 2}}
Badavala Nagar {2: {'mean': np.float64(6357.9277864992155), 'std': np.float64(0.0), 'count': 2}, 3: {'mean': np.float64(6279.828480978357), 'std': np.float64(42.27887875035828), 'count': 7}}
Balagere {1: {'mean': np.float64(5865.01000449379), 'std': np.float64(539.315075028032), 'count': 9}}
Balagere {1: {'mean': np.float64(5865.01000449379), 'std': np.float64(539.315075028032), 'count': 9}, 2: {'mean': np.float64(6524.604592622143), 'std': np.float64(269.2327263392672), 'count': 19}}
Banashankari {1: {'mean': np.float64(8333.333333333334), 'std': np.float64(0.0), 'count': 2}}
Banashankari {1: {'mean': np.float64(8333.333333333334), 'std': np.float64(0.0), 'count': 2}, 2: {'mean': np.float64(5038.253269278571), 'std': np.float64(1168.5163463486567), 'count': 31}}
Banashankari {1: {'mean': np.float64(8333.333333333334), 'std': np.float64(0.0), 'count': 2}, 2: {'mean': np.float64(5038.253269278571), 'std': np.float64(1168.5163463486567), 'count': 31}, 3: {'mean': np.float64(6562.960841828833), 'std': np.float64(1320.8589840659909), 'count': 21}}
Banashankari Stage II {2: {'mean': np.float64(8701.636799298034), 'std': np.float64(1030.287972433991), 'count': 4}}
Banashankari Stage II {2: {'mean': np.float64(8701.636799298034), 'std': np.float64(1030.287972433991), 'count': 4}, 3: {'mean': np.float64(10723.280423280425), 'std': np.float64(4231.90962768462), 'count': 6}}
Banashankari Stage II {2: {'mean': np.float64(8701.636799298034), 'std': np.float64(1030.287972433991), 'count': 4}, 3: {'mean': np.float64(10723.280423280425), 'std': np.float64(4231.90962768462), 'count': 6}, 4: {'mean': np.float64(12500.0), 'std': np.float64(0.0), 'count': 1}}

In [66]:
data.shape

(6732, 7)

In [67]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [68]:
data.drop(columns=['size', 'price_per_sqft'], inplace=True)

## Cleaned Data

In [70]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [71]:
data.to_csv("Cleaned_data.csv")

In [72]:
cleanedData = pd.read_csv('Cleaned_data.csv')

In [73]:
cleanedData.head()

   Unnamed: 0             location  total_sqft  bath  price  bhk
0           0  1st Block Jayanagar      2850.0   4.0  428.0    4
1           1  1st Block Jayanagar      1630.0   3.0  194.0    3
2           2  1st Block Jayanagar      1875.0   2.0  235.0    3
3           3  1st Block Jayanagar      1200.0   2.0  130.0    3
4           4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [74]:
X = data.drop(columns=['price'])
y = data['price']

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [77]:
print(X_train.shape)

(5385, 4)

In [78]:
print(X_test.shape)

(1347, 4)

## Applying Liner Regression